# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: wheels
  joint_model_group_pose: default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - summit_xl_back_left_wheel_joint
    - summit_xl_back_right_wheel_joint
    - summit_xl_front_left_wheel_joint
    - summit_xl_front_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: wheels_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - summit_xl_back_left_wheel_joint
      - summit_xl_back_right_wheel_joint
      - summit_xl_front_left_wheel_joint
      - summit_xl_front_right_wheel_joint